-- 1. List the number of films per category.
SELECT 
	c.name as category_name, 
    count(f.film_id) AS num_of_films
FROM sakila.film f
JOIN sakila.film_category as fc
	ON f.film_id = fc.film_id
JOIN sakila.category as c
	ON fc.category_id = c.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT
	s.store_id as store_id,
	ci.city,
    co.country as country
FROM sakila.store s
JOIN sakila.address a
	ON s.address_id = a.address_id
JOIN sakila.city ci
	ON a.city_id = ci.city_id
JOIN sakila.country co
	ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT
	s.store_id,
	sum(p.amount) as total_revenue
FROM sakila.store s
JOIN sakila.staff as st
	ON s.store_id = st.store_id
JOIN sakila.payment as p
	ON st.staff_id = p.staff_id
GROUP BY s.store_id;	

-- 4. Determine the average running time of films for each category.
SELECT 
	c.name as category,
    avg(f.length) as 'average running time'
FROM sakila.film f
JOIN sakila.film_category fc
	ON f.film_id = fc.film_id
JOIN sakila.category c
	ON fc.category_id = c.category_id
GROUP BY c.name;